type: R1Pro
# multi_view_cameras are used by BehaviorIterableDataset
multi_view_cameras:
  left_wrist: 
    name: robot_r1::robot_r1:left_realsense_link:Camera:0
    resolution: [240, 240]
  right_wrist: 
    name: robot_r1::robot_r1:right_realsense_link:Camera:0
    resolution: [240, 240]
  head: 
    name: robot_r1::robot_r1:zed_link:Camera:0
    resolution: [240, 240]
# action_keys and action_key_dims are used by the baselines in il_lib repo 
# You don't need to modify this if you are not training il_lib baselines
action_keys: [base, torso, left_arm, left_gripper, right_arm, right_gripper]
action_key_dims:
  base: 3
  torso: 4
  left_arm: 7
  left_gripper: 1
  right_arm: 7
  right_gripper: 1

# Overwrite below to modify the robot controller 
controllers:
  use_reward_regularization: false
  use_preprocessing: false
#  base:
#    name: HolonomicBaseJointController
#    motor_type: velocity # position, velocity
#    vel_kp: 150
##    pos_kp: 150
#    command_input_limits: [[-1.0, -1.0, -1.0], [1.0, 1.0, 1.0]]
#    command_output_limits: [[-0.75, -0.75, -1.0], [0.75, 0.75, 1.0]]
#    use_impedances: false
  base:
    name: HolonomicBaseJointController
    motor_type: position # position, velocity
    pos_kp: 50
    command_input_limits: null
    command_output_limits: null
    use_impedances: false
  trunk:
    name: JointController
    motor_type: position
    pos_kp: 150
    command_input_limits: default # null
    command_output_limits: default # null
    use_impedances: false
    use_delta_commands: false
  arm_left:
    name: JointController
    motor_type: position
    pos_kp: 150
    command_input_limits: default # null
    command_output_limits: default # null
    use_impedances: false
    use_delta_commands: false
  arm_right:
    name: JointController
    motor_type: position
    pos_kp: 150
    command_input_limits: default # null
    command_output_limits: default # null
    use_impedances: false
    use_delta_commands: false
  gripper_left:
    name: MultiFingerGripperController
    mode: smooth
    command_input_limits: default
    command_output_limits: default
  gripper_right:
    name: MultiFingerGripperController
    mode: smooth
    command_input_limits: default
    command_output_limits: default